### ISSUE TITLE
FS.getCurrentSessionURL is not a function

### ISSUE THREAD

**Issue by shangHai-F** [getsentry/sentry-fullstory#55]
I'm pretty sure FS already exists, why when I use FS.getCurrentSessionURL(true), FS.getCurrentSessionURL is not a function still appears

**Comment by patrick-fs** [comment]
Hi @shangHai-F. Yes `FS` exists as soon as the FullStory snippet is executed in the browser. However, the `getCurrentSessionURL` function is defined some time after the snippet executes.

There's a comment about this in the source code for the sentry-fullstory integration: https://github.com/getsentry/sentry-fullstory/blob/master/src/SentryFullStory.ts#L56

If you're using the `@fullstory/browser` NPM package, calling `getCurrentSessionURL` on the package won't throw an error. Rather, it will return a null value if `getCurrentSessionURL` isn't ready.

More information about the FullStory browser bootstrapping process can be found here: https://help.fullstory.com/hc/en-us/articles/360032975773-How-does-FullStory-recording-work-to-recreate-my-users-experience-

`getCurrentSessionURL` isn't ready until after step 3:

![image](https://user-images.githubusercontent.com/45576380/125313464-3e9fd000-e303-11eb-9635-ceaf5185040b.png)

**Comment by shangHai-F** [comment]
@patrick-fs I see, thank you very much,.

**Comment by igrayson** [comment]
@patrick-fs I think this behavior has changed, or maybe always had an edge case where it failed.

If an error is thrown and processed by sentry between step 1 and 2 in the diagram you pasted, `FS.getCurrentSessionURL` will throw. [Here's an example](https://sentry.io/share/issue/7d275df637c9438ba98eb3d403ed9ff6/).

The error isn't the same as the OP, but the issue is basically the same.

Would you consider a PR that checked that FS was fully loaded (`!!window[window._fs_namespace]`) before attempting to call fullstory APIs?
